# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ĝi estas Blogo
baseurl:          /

exclude: [ _locale , _scripts , "*.backup" ]

url: "https://jmichault.github.io/motioneye.eo"

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true
