# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Ĝi estas Blogo
baseurl:          /motioneye.eo

exclude: [ _locale , _scripts , "*.backup" ]

plugins:
  - jekyll-relative-links
  - jekyll-sitemap

relative_links:
  enabled:     true
  collections: true
